### ISSUE TITLE
KVEmptyTest.SizeofTest failure

### ISSUE THREAD

**Issue by luohao** [pmem/pmemkv#56]
I hit one unit test failure in the latest pmemkv (actually I notice this failure long time ago).
The size of KVInnerNode on my machine is indeed 112 since the struct is not packed, not sure why expecting 232.
```
sizeof(KVInneNode) = 8 + 8 + 8 + 5*8 + 6 * 8 = 112
```
Erro message:
```
[ RUN      ] KVEmptyTest.SizeofTest
pmemkv_test.cc:140: Failure
Value of: 232
Expected: sizeof(KVInnerNode)
Which is: 112
[  FAILED  ] KVEmptyTest.SizeofTest (0 ms)
```
Setup:
```
  - i7-4770 CPU
  - CentOS 7 with kernel 3.10.0-514.2.2.el7.x86_64
  - gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) 
```

**Comment by RobDickinson** [comment]
Hi @luohao, thank you so much for reporting this problem and for the detailed description.  I'm not sure off the top of my head why this is breaking, but we will investigate further.  I will let you know through comments on this issue if we have any questions.

**Comment by RobDickinson** [comment]
This was a classic mistake on my part -- the problem is that `sizeof(std::string)` can be either 8 or 32 depending on the platform/compiler.  Therefore `sizeof(KVInnerNode)` can be 112 or 232.

After taking some time to think, I'm voting to remove the SizeofTest as a standard test altogether.  As it turns out, there isn't any actual logic in `pmemkv` that relies on the specific sizes of structures.  This test was helpful in the very early design phase, but we have better ways of validating changes to data structures nowadays.

@luohao, thank you so much for raising this issue!  I hate for a broken unit test to be your first experience with `pmemkv`, and we're very grateful that you took the time to log this bug.
