### ISSUE TITLE
why we must rely on intel TBB lib?

### ISSUE THREAD

**Issue by gwnet** [pmem/pmemkv#627]
can we remove it to build?

**Comment by igchor** [comment]
Yes, this is optional dependency needed only if you want to use vcmap. You can pass -DENGINE_VCMAP=0 to disable it.

**Comment by gwnet** [comment]
thank you so much. I found that last night. may I know what is the difference between VCMAP and VSMAP. what I looking forward most is the concurrent skiplist. may I know if we already support it well?

**Comment by vinser52** [comment]
1. VCMAP is a volatile concurrent unsorted engine that does not support range operations (like get_above, get_below, get_between, etc). Internally, it is built on top of Intel TBB concurrent_hash_map.
2. VSMAP is a volatile sorted engine that does not support concurrent operations but supports range operations. Internally, it is built on top of ```std::map``` with ```libmemkind::pmem::allocator```.

Both volatile engines mentioned above does not restore the state after process restart. They are targeted to store volatile data on pmem and reduce the usage of DRAM.

Since you mentioned concurrent skip-list, could you please describe your use case in more detail? Are you interested in a persistent concurrent skip list or volatile one? Today, Intel TBB already has concurrent_map implementation based on the concurrent skip list. And we are working on a persistent version of the concurrent skip list (see [PR423 to libpmemobj-cpp](https://github.com/pmem/libpmemobj-cpp/pull/423)).

**Comment by gwnet** [comment]
we want to use K-V store. previously we use RocksDB similar thing, the sequence is insert journal, insert mem table, when memtable is full, we dump it into disks with btree. so if we use pmemkv, we want to use one thing to replace 3 steps before. skiplist is one good structure for us, it is RocksDB default implementation. so we want to use pmemkv's skiplist implementation. 
BTW, have intel try to improve RocksDB with pmem?

**Comment by vinser52** [comment]
Thank you for your reply. We are working on the productization of the persistent concurrent skip list.
If you want to play with our prototype today you can install libpmemobj-cpp from my [development branch](https://github.com/vinser52/libpmemobj-cpp/tree/concurrent_map) and pmemkv with [the prototype of the csmap engine](https://github.com/vinser52/pmemkv/tree/csmap_engine)

**Comment by gwnet** [comment]
thank you so much. I will play it.

**Comment by lukaszstolarczuk** [comment]
It seems like the original question is answered, so I'll allow myself to close this issue. If you feel differently and want to continue don't hesitate to ask once more.
