### ISSUE TITLE
Ran pmemkv on EXT4 DAX but failed with segment fault

### ISSUE THREAD

**Issue by lh2debug** [pmem/pmemkv#76]
I ran pmemkv on my file system "ext4 dax" but failed with segment fault. What kind of DAX file system does pmemkv support? And what kind of device supports DAX file system? Thank you !!!

I use these commands to set up file system "ext4 dax":
```
mkfs.ext4 /dev/pmem0
mount -o dax /dev/pmem0 /mnt/pmem/
```

I change code in fuction KVTree::KVTree of "kvtree.cc"(pathname of dax is different):

```
    if (path.find("/dev/dax") == 0) {
        LOG("Opening device dax pool, path=" << path);
        pmpool = pool<KVRoot>::open(path.c_str(), LAYOUT);
        pmsize = 0;
    } else if (access(path.c_str(), F_OK) != 0) {
        LOG("Creating filesystem pool, path=" << path << ", size=" << to_string(size));
        pmpool = pool<KVRoot>::create(path.c_str(), LAYOUT, size, S_IRWXU);
        pmsize = size;
    } else {
        LOG("Opening filesystem pool, path=" << path);
        pmpool = pool<KVRoot>::open(path.c_str(), LAYOUT);
        struct stat st;
        stat(path.c_str(), &st);
        pmsize = (size_t) st.st_size;
    }
```
to 
```
    if (path.find("/mnt/pmem") == 0) {
        LOG("Opening device dax pool, path=" << path);
        pmpool = pool<KVRoot>::open(path.c_str(), LAYOUT);
        pmsize = 0;
    } else if (access(path.c_str(), F_OK) != 0) {
        LOG("Creating filesystem pool, path=" << path << ", size=" << to_string(size));
        pmpool = pool<KVRoot>::create(path.c_str(), LAYOUT, size, S_IRWXU);
        pmsize = size;
    } else {
        LOG("Opening filesystem pool, path=" << path);
        pmpool = pool<KVRoot>::open(path.c_str(), LAYOUT);
        struct stat st;
        stat(path.c_str(), &st);
        pmsize = (size_t) st.st_size;
    }
```

**Comment by lh2debug** [comment]
Thank you for your detailed reply. Is your dax device that pmemkv supports for sale ? What is the difference  of performances between pmemkv on dax device and pmemkv on file system dax? 

Test  on file system DAX:
```
[root@localhost pmemkv]# PMEM_IS_PMEM_FORCE=1 ./pmemkv_bench --db=/mnt/pmem/pmemkv --num=100000 --value_size=1000
Date:       Fri Apr 20 14:43:14 2018
CPU:        24 * Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz
CPUCache:   15360 KB
Path:       /mnt/pmem/pmemkv
Engine:     kvtree
Keys:       16 bytes each
Values:     1000 bytes each
Entries:    100000
RawSize:    96.9 MB (estimated)
------------------------------------------------
removed      :     338.558 millis/op;
open         :      20.095 millis/op;
fillrandom   :      23.452 micros/op;   41.3 MB/s
overwrite    :      23.683 micros/op;   40.9 MB/s
removed      :       0.058 millis/op;
open         :      20.288 millis/op;
fillseq      :      21.037 micros/op;   46.1 MB/s
readrandom   :       1.738 micros/op;  557.4 MB/s (100000 of 100000 found)
readseq      :       1.720 micros/op;  563.3 MB/s (100000 of 100000 found)
readrandom   :       1.950 micros/op;  496.9 MB/s (100000 of 100000 found)
readmissing  :       1.390 micros/op;   11.7 MB/s (0 of 100000 found)
readrandom   :       2.584 micros/op;  375.0 MB/s (100000 of 100000 found)
deleteseq    :      12.907 micros/op;
```

**Comment by RobDickinson** [comment]
Any NVDIMM device (from Intel or another vendor) can be used with either filesystem DAX or device DAX.  (DAX is an open standard)

There's no significant performance difference between filesystem and device DAX.

The main difference between filesystem and device DAX is how they are used by the application.  Filesystem DAX supports user permissions and standard filesystem utilities (like df) and allows creating multiple files to partition memory into regions.  Device DAX is just a raw device that doesn't support permission checks or standard filesystem utilities, and any partitioning has to be done by the application.

My recommendation is that if you're adapting a database (or similar application) that uses raw devices, then device DAX will fit those expectations well.  But for most cases filesystem DAX is going to be more useful -- given that it has the same performance as device DAX, offers easier management, and more applications are written to use file systems instead of managing entire raw devices.  So you can use either device or filesystem DAX, but in reality filesystem DAX is far more popular.

ps.  There were some reasons historically where filesystem DAX could be significantly slower than device DAX, but those have been resolved and in the modern context these offer the same performance.

Hope this helps.
RobD

**Comment by lh2debug** [comment]
Thank you very much, hope  the development of pmdk and pmemkv is getting better!
