### ISSUE TITLE
What is separate visibility bitmap in FPTree that you mentions in ENGINES.md ?

### ISSUE THREAD

**Issue by williamhli** [pmem/pmemkv#77]
First of all, thank you for your contribution to nvm research, I read pmemkv/ENGINES.md and it mentions that FPTree uses an array of key hashes with a separate visibility bitmap to track what hash slots are occupied. What is separate visibility bitmap ? What is the difference with original bitmap ?Thank you!

**Comment by RobDickinson** [comment]
No code for `FPTree` was ever released, just a paper describing its design -- but in this paper, the authors describe a visibility bitmap that denotes what slots in the leaf are occupied, and then there is a separate array of single-byte hashes for all occupied slots.  So when reading, first you check the visibility bitmap, then you check against the hash, then you'll read the slot.  Updates go the opposite way, first updating the slot, then the hash, then flipping a bit in the visibility bitmap.

For the `KVTree` engine, we simplified this approach a bit.  Here we apply a modified Pearson hash, where a hash value of 0 is assigned the special meaning that the slot is empty.  This slightly increases the chances of getting a hash collision, but allows us to represent both the visibility bitmap and the array of hashes using just the array of hashes.  Therefore `KVTree` can just read the hashes as a single cacheline (without having to access a second cacheline for the visibility bitmap) and just sets hashes on update (without having to twiddle bits in the visibility bitmap).

To be fair, it's possible that `FPTree` used a similar approach -- the paper does not describe the hash function implementation, and this seems a fairly obvious optimization to fold the visibility bitmap and the set of hashes together.  There's no choice but to guess since the original `FPTree` code was never released.

**Comment by williamhli** [comment]
Thank you for your answer!
