### ISSUE TITLE
What caused most of pmdk’s overhead ? pmemkv is slower than pmemkv on pool based malloc/free.

### ISSUE THREAD

**Issue by williamhli** [pmem/pmemkv#78]
The performance of pmemkv on file system dax(ramdisk, basically on DRAM ) is not fast enough. Especially the writing speed is slow. The speed of randwrite is 40M/s on my device. Whereas the speed of randwrite on pmemkv in memory pool based on malloc/free is 200M/s to 300M/s.I use fio tool to test randwrite the raw memory and the speed is about 300MB/s.(The size of kv is 1KB)。
What caused most of pmdk’s overhead ? Thank you!

benchmark test on pmemkv (the size of kv is 1KB):
```
[root@server205 pmemkv]# PMEM_IS_PMEM_FORCE=1 ./pmemkv_bench --db=/mnt/pmem/pmemkv --num=100000 --value_size=1000
Date:       Fri Apr 20 16:16:14 2018
CPU:        24 * Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz
CPUCache:   15360 KB
Path:       /mnt/pmem/pmemkv
Engine:     kvtree
Keys:       16 bytes each
Values:     1000 bytes each
Entries:    100000
RawSize:    96.9 MB (estimated)
------------------------------------------------
removed      :      29.527 millis/op;
open         :      19.866 millis/op;
fillrandom   :      22.197 micros/op;   43.7 MB/s
overwrite    :      22.441 micros/op;   43.2 MB/s
removed      :       0.043 millis/op;
open         :      12.115 millis/op;
fillseq      :      18.119 micros/op;   53.5 MB/s
readrandom   :       1.798 micros/op;  538.9 MB/s (100000 of 100000 found)
readseq      :       1.720 micros/op;  563.3 MB/s (100000 of 100000 found)
readrandom   :       1.562 micros/op;  620.2 MB/s (100000 of 100000 found)
readmissing  :       1.384 micros/op;   11.7 MB/s (0 of 100000 found)
readrandom   :       2.015 micros/op;  480.8 MB/s (100000 of 100000 found)
deleteseq    :      13.265 micros/op;
```
Fio test:
```
mytest: (g=0): rw=randwrite, bs=1K-1K/1K-1K/1K-1K, ioengine=psync, iodepth=1
fio-2.2.10
Starting 1 thread
mytest: Laying out IO file(s) (1 file(s) / 2048MB)

mytest: (groupid=0, jobs=1): err= 0: pid=17608: Fri Apr 20 15:08:56 2018
  write: io=2048.0MB, bw=329017KB/s, iops=329016, runt=  6374msec
    clat (usec): min=1, max=146, avg= 2.32, stdev= 0.95
     lat (usec): min=1, max=147, avg= 2.37, stdev= 0.95
    clat percentiles (usec):
     |  1.00th=[    1],  5.00th=[    1], 10.00th=[    2], 20.00th=[    2],
     | 30.00th=[    2], 40.00th=[    2], 50.00th=[    2], 60.00th=[    2],
     | 70.00th=[    2], 80.00th=[    3], 90.00th=[    3], 95.00th=[    4],
     | 99.00th=[    6], 99.50th=[    6], 99.90th=[    7], 99.95th=[    8],
     | 99.99th=[   11]
    bw (KB  /s): min=30696, max=409858, per=98.09%, avg=322743.67, stdev=104402.61
    lat (usec) : 2=7.47%, 4=86.24%, 10=6.26%, 20=0.03%, 50=0.01%
    lat (usec) : 100=0.01%, 250=0.01%
  cpu          : usr=24.40%, sys=75.58%, ctx=9, majf=0, minf=161
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=0/w=2097152/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: io=2048.0MB, aggrb=329016KB/s, minb=329016KB/s, maxb=329016KB/s, mint=6374msec, maxt=6374msec
```

**Comment by RobDickinson** [comment]
Great question!

With the `KVTree` engine, a put operation is transactional.  Each put operation will fully succeed or be completely rolled back so that the tree is always in a consistent state.  There's no eventual consistency options (yet) that would allow relaxing this guarantee in favor of higher write performance.  So pmemkv is like running RocksDB with sync=1 or Redis with fsync always -- those configurations offer the same kind of safe consistency but are known to be intolerably slow (but on persistent memory are more practical).

So when you're comparing against FIO, it's not really an apples-to-apples comparison.  FIO is merely writing out blocks of data in linear fashion without any transactional guarantees, whereas pmemkv is using transactions to update shared data structures in place.

I'd also volunteer that `KVTree` was a first attempt, and initially we were most concerned with optimizing read performance (which is quite good).  We have a newer copy-on-write engine which currently offers about 2x the write performance, while still remaining strongly consistent.  You can use this alternative engine by passing `--engine=btree` as a parameter to `pmemkv_bench`.  (Be aware though that the `btree` engine still has some rough edges, like the remove operation is not yet implemented)

There are also significant performance improvements coming in the next major version of PMDK that speed up the pmemobj memory allocator and transaction facility, which represents most of the time spent in a pmemkv put operation.

There are also ideas for engines that might use more than one pool, or have relaxed consistency guarantees, but at this point those are still on the drawing board.

A big part of understanding performance is understanding the use-case, so if you're able to share more details about the kinds of workloads you're hoping to optimize, I might be able to make some further suggestions.

Anyway, hopefully this helps!
RobD

**Comment by lh2debug** [comment]
Thank you for your professional reply. Looking forward to further communication with you.

**Comment by williamhli** [comment]
Thank you for your professional reply. Looking forward to further communication with you.
